name: Build Android APK
on:
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4 # تحديث إلى v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # تحديث إلى v4
        with:
          node-version: 20 # استخدام نسخة حديثة ومستقرة

      - name: Install Dependencies
        run: npm install

      - name: Build Web Project
        run: npm run build 

      - name: Capacitor Sync
        run: npx cap sync android 

      - name: Build Android APK
        run: |
          cd android && ./gradlew assembleDebug 

      - name: Upload APK
        uses: actions/upload-artifact@v4 # الحل الأساسي: التحديث إلى v4
        with:
          name: TMS-App-Jood
          path: android/app/build/outputs/apk/debug/app-debug.apk
